apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-verification
  namespace: monitoring
data:
  verification-results.md: |
    # Monitoring and Alerting Verification Report

    ## Prometheus Setup
    - [x] Metrics collection active
    - [x] Service discovery working
    - [x] Target scraping successful
    - [x] Data retention configured
    - [x] HA configuration verified
    - [x] Resource usage optimized
    - [x] Security rules enforced
    - [x] Backup configured

    ## Grafana Configuration
    - [x] Dashboards loaded
      - System Overview
      - Security Metrics
      - AI Service Performance
      - WebSocket Metrics
      - User Activity
      - Resource Usage
    - [x] Data sources connected
    - [x] Alert channels configured
    - [x] User access configured
    - [x] Backup enabled

    ## Alert Rules
    ### Critical Alerts
    - [x] Service downtime
    - [x] High error rates
    - [x] Resource exhaustion
    - [x] Security violations
    - [x] Certificate expiry
    - [x] Backup failures

    ### Warning Alerts
    - [x] High latency
    - [x] Resource pressure
    - [x] API rate limiting
    - [x] Auth failures
    - [x] Model accuracy
    - [x] Connection issues

    ## Logging System
    - [x] ELK stack operational
    - [x] Log shipping verified
    - [x] Log retention set
    - [x] Search working
    - [x] Alerts configured
    - [x] Security logging active

    ## Custom Metrics
    - [x] AI model performance
    - [x] WebSocket connections
    - [x] Media stream quality
    - [x] Authentication rates
    - [x] Resource efficiency
    - [x] User experience

  alert-verification.md: |
    # Alert Rule Verification

    ## System Alerts
    ```yaml
    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
        description: Error rate is above 5%

    - alert: HighLatency
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected
        description: 95th percentile latency is above 500ms

    - alert: ResourceExhaustion
      expr: sum(container_memory_usage_bytes) by (pod) / sum(container_memory_limit_bytes) by (pod) > 0.85
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: High resource usage
        description: Container using more than 85% of memory limit
    ```

    ## AI Service Alerts
    ```yaml
    - alert: LowModelAccuracy
      expr: model_accuracy < 0.95
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Low model accuracy
        description: AI model accuracy below 95%

    - alert: HighInferenceLatency
      expr: histogram_quantile(0.95, sum(rate(model_inference_duration_seconds_bucket[5m])) by (le)) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High inference latency
        description: Model inference taking longer than 100ms
    ```

  dashboard-verification.md: |
    # Dashboard Verification

    ## System Overview
    - Resource usage trends
    - Error rates and latencies
    - Request volumes
    - Service health status

    ## Security Dashboard
    - Authentication attempts
    - Security violations
    - Certificate status
    - Network policy hits

    ## AI Service Performance
    - Model accuracy metrics
    - Inference latency
    - GPU utilization
    - Batch processing rates

    ## User Activity
    - Active sessions
    - WebSocket connections
    - Media stream quality
    - Test completion rates
