apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ayphen-admin
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ayphen-viewer
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ayphen-admin-binding
subjects:
- kind: ServiceAccount
  name: ayphen-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: ayphen-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ayphen-viewer-binding
subjects:
- kind: ServiceAccount
  name: ayphen-viewer
  namespace: default
roleRef:
  kind: ClusterRole
  name: ayphen-viewer
  apiGroup: rbac.authorization.k8s.io
