apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: "0 1 * * *"  # Daily at 1 AM
  template:
    includedNamespaces:
    - default
    - monitoring
    includedResources:
    - deployments
    - statefulsets
    - configmaps
    - secrets
    - persistentvolumeclaims
    labelSelector:
      matchLabels:
        app.kubernetes.io/part-of: ayphen-hire
    storageLocation: default
    volumeSnapshotLocations:
    - default
    ttl: 720h  # 30 days
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: ayphen-hire-backups
  config:
    region: us-west-2
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=${AWS_ACCESS_KEY_ID}
    aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup
  namespace: default
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup
            image: bitnami/postgresql:latest
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} | gzip > /backup/db-$(date +%Y%m%d).sql.gz
              aws s3 cp /backup/db-$(date +%Y%m%d).sql.gz s3://ayphen-hire-backups/databases/
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: ayphen-app-secrets
                  key: DB_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backup-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-credentials
                  key: AWS_SECRET_ACCESS_KEY
            volumeMounts:
            - name: backup
              mountPath: /backup
          volumes:
          - name: backup
            emptyDir: {}
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-models-backup
  namespace: default
spec:
  schedule: "0 3 * * 0"  # Weekly on Sunday at 3 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: model-backup
            image: amazon/aws-cli:latest
            command:
            - /bin/sh
            - -c
            - |
              aws s3 sync /models s3://ayphen-hire-backups/models/
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backup-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-credentials
                  key: AWS_SECRET_ACCESS_KEY
            volumeMounts:
            - name: models
              mountPath: /models
              readOnly: true
          volumes:
          - name: models
            persistentVolumeClaim:
              claimName: ai-models-pvc
          restartPolicy: OnFailure
